name: Node CI

on:
  push:
    branches:
      - master
      - develop
      - beta
      - 'feature/**'
      - 'release/**'

jobs:
  prepare_version:
    name: Prepare Version
    runs-on: ubuntu-18.04
    if: "!contains(github.actor, 'process-engine-ci') || contains(github.actor, 'admin')"

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: |
        npm ci
        ./node_modules/.bin/ci_tools npm-install-only --except-on-primary-branches @process-engine/ @essential-projects/

    - name: Prepare version
      run: |
        ./node_modules/.bin/ci_tools prepare-version --allow-dirty-workdir

    - name: Get package version
      run: echo "##[set-output name=version;]$(node --print --eval "require('./package.json').version")"
      id: package_version

    - name: Log Version
      run: |
        echo $VERSION
      env:
        VERSION: ${{ steps.package_version.outputs.version }}

    - name: Stash package.json
      uses: actions/upload-artifact@master
      with:
        name: package_json
        path: package.json

  lint_linux:
    name: "Lint sources"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - run: npm run lint
      name: Lint sources

  test_sqlite:
    name: "Test with SQLite"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Build
      run: |
        npm run build
        npm rebuild

    - name: Run tests
      run: npm run test-sqlite

  test_postgres:
    name: "Test with Postgres"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Build
      run: npm run build

    - name: Start Postgres Docker Container
      run: |
        docker run -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=admin -e POSTGRES_USER=admin -e POSTGRES_DB=processengine -d postgres:11
        docker ps

    - name: Run tests
      run: npm run test-postgres

    - run: |
        docker ps -a
        docker logs postgres
      if: always()

  test_mysql:
    name: "Test with MySQL"
    needs: prepare_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Build
      run: npm run build

    - run: mv config/test-mysql/.my.cnf ~/.my.cnf

    - run: echo "create database processengine" | mysql

    - name: Run tests
      run: npm run test-mysql

  create_sources_linux:
    name: "Create tarball from linux sources"
    needs: prepare_version
    runs-on: ubuntu-18.04
    if: contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'beta')

    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Build
      run: |
        npm run build
        npm rebuild
        npm run create-tarball

    - name: Stash Tarball
      uses: actions/upload-artifact@master
      with:
        name: process_engine_runtime_linux_tar
        path: process_engine_runtime_linux.tar.gz

  create_sources_macos:
    name: "Create tarball from macOS sources"
    needs: prepare_version
    runs-on: macOS-latest
    if: contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'beta')

    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Build
      run: |
        npm run build
        npm rebuild
        npm run create-tarball

    - name: Stash Tarball
      uses: actions/upload-artifact@master
      with:
        name: process_engine_runtime_macos_tar
        path: process_engine_runtime_macos.tar.gz

  create_windows_sources:
    name: "Create Windows Sources"
    needs: prepare_version
    runs-on: windows-latest
    #if: contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'beta')

    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Build
      run: |
        npm run build
        npm rebuild

    - name: Cache sources
      uses: actions/cache@v1
      with:
        path: '.'
        key: workdir-windows
        # stash sources
        #${{ github.workspace }}
    #- name: Stash Tarball
    #  uses: actions/upload-artifact@master
    #  with:
    #    name: process_engine_runtime_windows_zip
    #    path: process_engine_runtime_windows.zip

  create_windows_zip:
    name: "Create zip file from Windows sources"
    needs: create_windows_sources
    runs-on: macos-latest
    #if: contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'beta')

    steps:
    - uses: actions/checkout@master

    - name: Cache sources
      uses: actions/cache@v1
      with:
        path: '.'
        key: workdir-windows
# cache einsetzen
    - name: Create zip file
      run: npm run create-zipfile

    - name: Stash Tarball
      uses: actions/upload-artifact@master
      with:
        name: process_engine_runtime_windows_zip
        path: process_engine_runtime_windows.zip

  build_windows_installer:
    name: "Build Windows installer"
    needs: prepare_version
    runs-on: windows-latest
    if: contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'beta')

    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Install npm dependencies
      run: |
        cat package.json
        npm i

    - name: Build
      shell: cmd
      run: |
        npm run build
        npm rebuild

    - name: Build Executable
      run: npm run build-windows-executable

    - name: Get package version
      run: echo "##[set-output name=version;]$(node --print --eval "require('./package.json').version")"
      id: package_version

    - name: Build Installer
      run: iscc "/DProcessEngineRuntimeVersion=%full_release_version_string%" installer\\inno-installer.iss
      shell: cmd
      env:
        full_release_version_string: ${{ steps.package_version.outputs.version }}

    - name: Stash Installer
      uses: actions/upload-artifact@master
      with:
        name: windows_installer_results
        path: installer/Output

  prepare_and_tag_version:
    name: "Commit & Tag Version"
    needs: [lint_linux, build_windows_installer, create_windows_zip, create_sources_linux, create_sources_macos, test_sqlite, test_postgres]
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Commit and Tag
      run: |
        ./node_modules/.bin/ci_tools commit-and-tag-version --only-on-primary-branches
      env:
        GH_USER: ${{ secrets.GH_USER }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

  publish_npm:
    name: "Publish npm package"
    needs: prepare_and_tag_version
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Publish npm package
      run: ./node_modules/.bin/ci_tools publish-npm-package --create-tag-from-branch-name
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_github:
    name: "Publish GitHub Release"
    needs: prepare_and_tag_version
    runs-on: ubuntu-18.04
    if: contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'beta')

    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Unstash Linux Sources
      uses: actions/download-artifact@master
      with:
        name: process_engine_runtime_linux_tar
        path: "dist"

    - name: Unstash macOS Sources
      uses: actions/download-artifact@master
      with:
        name: process_engine_runtime_macos_tar
        path: "dist"

    - name: Unstash Windows Sources
      uses: actions/download-artifact@master
      with:
        name: process_engine_runtime_windows_zip
        path: "dist"

    - name: Unstash Windows Installer
      uses: actions/download-artifact@master
      with:
        name: windows_installer_results
        path: "dist"

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: npm-${{ hashFiles('package-lock.json') }}

    - name: Upload to GitHub
      run: |
        ./node_modules/.bin/ci_tools update-github-release --only-on-primary-branches --use-title-and-text-from-git-tag
        ./node_modules/.bin/ci_tools update-github-release \
                              --assets dist/Install ProcessEngine Runtime**.exe \
                              --assets dist/process_engine_runtime_macos.tar.gz \
                              --assets dist/process_engine_runtime_linux.tar.gz \
                              --assets dist/process_engine_runtime_windows.zip
      env:
        GH_USER: ${{ secrets.GH_USER }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build_docker:
    name: "Build & Publish Docker Image"
    needs: prepare_and_tag_version
    runs-on: ubuntu-18.04
    if: contains(github.ref, 'master') || contains(github.ref, 'develop') || contains(github.ref, 'beta')
    steps:
    - uses: actions/checkout@master

    - name: Unstash package.json
      uses: actions/download-artifact@master
      with:
        name: package_json
        path: "."

    - name: Unstash Linux Sources
      uses: actions/download-artifact@master
      with:
        name: process_engine_runtime_linux_tar
        path: "."

    - name: Get package version
      run: echo "##[set-output name=version;]$(node --print --eval "require('./package.json').version")"
      id: package_version

    - name: Build Docker Image
      run: |
        docker build --build-arg NODE_IMAGE_VERSION=10-alpine \
                    --build-arg PROCESS_ENGINE_VERSION=$VERSION \
                    --no-cache \
                    --tag 5minds/process_engine_runtime:$VERSION .
      env:
        VERSION: ${{ steps.package_version.outputs.version }}

    - name: Show Docker Images
      run: docker images

    - name: Login to Docker
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    - name: Push Docker Image
      run: docker push 5minds/process_engine_runtime
